### ISSUE TITLE
Please document the usage of @text

### ISSUE THREAD

**Issue by brlin-tw** [orf/html-query#78]
I had to dig through [the source code](https://github.com/orf/hq/blob/68007abdc73970a5b4dbd5ffb4c2c9b9bd1486ad/html-query-ast/src/parser.rs#L24) for this syntax that does exactly what I want, it should really be documented in the README.

Example usage:

```bash
# Parse out all the text of the Git glossary terms
curl -s https://git-scm.com/docs/gitglossary \
    | hq '{ headings: dt.hdlist1 | [{ text: @text }] }' \
    | jq --raw-output '.headings[].text'
```

**Comment by orf** [comment]
Good shout! I'll add it!
