### ISSUE TITLE
Please mark html-query-1.2.1 as the latest release

### ISSUE THREAD

**Issue by brlin-tw** [orf/html-query#85]
Currently, the 1.2.0 version is marked as the latest release on [the releases page](https://github.com/orf/html-query/releases):

![Screenshot that depicts the problem where the 1.2.0 version is being marked as "the latest release" on the project's releases page](https://github.com/orf/html-query/assets/13408130/afb44c60-565d-4a7c-9c25-72d8c4fb08f0 "Screenshot that depicts the problem")

As [the 1.2.0 version has a major problem that is fixed in 1.2.1(unintended output printed to stdout)](https://github.com/orf/html-query/commit/321a20ba36a2d5b368795a5d251d80941f82f3c5), marking 1.2.1 as the latest release so the users would not encounter it.

Thanks in advance!

**Comment by orf** [comment]
Sure! Should be done very shortly.
